# Generated by Django 3.1.3 on 2023-08-29 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0004_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fuzz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('fuzz_type', models.IntegerField(default=0)),
                ('fuzz_content', models.CharField(max_length=10000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_time', models.CharField(max_length=100)),
                ('sum_time', models.CharField(max_length=10)),
                ('passed', models.IntegerField(default=0)),
                ('failed', models.IntegerField(default=0)),
                ('no_check', models.IntegerField(default=0)),
                ('log', models.CharField(max_length=100, null=True)),
                ('report_path', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Suite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_fuzz', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('task_state', models.IntegerField(default=0)),
                ('task_type', models.IntegerField(default=0)),
                ('start_time', models.CharField(max_length=100, null=True)),
                ('sum_time', models.CharField(max_length=100, null=True)),
                ('suite', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='TestModel.suite')),
            ],
        ),
        migrations.CreateModel(
            name='ReportItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=100)),
                ('protocol', models.CharField(max_length=10)),
                ('method', models.CharField(max_length=10)),
                ('params', models.CharField(max_length=1000)),
                ('hope', models.CharField(max_length=100)),
                ('sum_time', models.CharField(max_length=50)),
                ('fact', models.CharField(max_length=10000)),
                ('result', models.IntegerField(default=0)),
                ('report', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='TestModel.report')),
            ],
        ),
        migrations.AddField(
            model_name='report',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='TestModel.task'),
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=100)),
                ('protocol', models.CharField(max_length=10)),
                ('method', models.CharField(max_length=10)),
                ('params', models.CharField(max_length=1000)),
                ('hope', models.CharField(max_length=1000, null=True)),
                ('suite', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='TestModel.suite')),
            ],
        ),
    ]
