# Generated by Django 3.1.3 on 2023-08-31 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0007_auto_20230831_0858'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiLogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=300)),
                ('params', models.CharField(max_length=10000)),
                ('method', models.CharField(max_length=10)),
            ],
        ),
    ]
