# Generated by Django 3.1.3 on 2023-09-01 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0008_apilogin'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=300)),
                ('params', models.CharField(max_length=10000)),
                ('method', models.CharField(max_length=10)),
            ],
        ),
    ]
