# Generated by Django 3.1.3 on 2023-09-01 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0009_apitest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApiTest',
        ),
    ]
