# Generated by Django 3.1.3 on 2023-09-04 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0010_delete_apitest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='failed',
            new_name='sum_fail',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='no_check',
            new_name='sum_no_check',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='passed',
            new_name='sum_pass',
        ),
    ]
